<?php
/**
 *  log.php
 *  @author Greg Meadows
 *  @copyright 2019 Greg Meadows
 *  @link http://gregmeadows.uk
 */

/**
 *  Used to log an error and optionally send an email notification.
 *
 *  PARAMETER        :  EXAMPLE  :  DEFINITION
 *  @param $errorID  :  403      :  The alphanumerical representation for the type of error
 *  @param $email    :  true     :  Should an email notification be sent
 */
function logError($errorID = 0, $email = false) {
    
    // Email variables
    $logDIR = 'logs/';
    $emailTo = base64_decode("YWxlcnRAZ3JlZ21lYWRvd3MudWs=");
    $emailFrom = base64_decode("YWxlcnRAZ3JlZ21lYWRvd3MudWs=");
    $subject = "GregMeadows.uk: $errorID Reported";
    
    // Organise info into an array
    $errorData = array (
        'http_add' => $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'],
    );  
      
    // Get extra error info
    $errorInfo = array (
        'user_ip' => 'REMOTE_ADDR',
        'user_agent' => 'HTTP_USER_AGENT',
        'link_ref' => 'HTTP_REFERER',
        'path_info' => 'PATH_INFO',
        'forwarding' => 'HTTP_X_FORWARDED_FOR',
        'method' => 'REQUEST_METHOD',
        'software' => 'SERVER_SOFTWARE',
        'remote_host' => 'REMOTE_HOST',
        'uri_query' => 'QUERY_STRING'
    ); 
    
    // Iterate through extra info to find valid results
    foreach ($errorInfo as $title => $value) {
        if(isset($_SERVER[$value]) && !empty($_SERVER[$value])){
            $errorData[$title] = $_SERVER[$value];
        }
    }
    
    // Get any POST data
    $errorPost = file_get_contents('php://input');
    if ($errorPost) $errorData['post_data'] = $errorPost;
    
    // Add to log
    error_log("[" . date('d.m.y \a\t H:i:s') . "] Error $errorID " . print_r($errorData, true) . "\n", 3, "$logDIR$errorID.log");
    
    // Email error if set to true
    if ($email) {
        
        // Get date and time
        $dtStamp = date('d F Y \a\t H:i:s');
        
        // Create HTML Email
        $message = <<< HTML
            <html>
            <head>
            <style>
            table, th, td {
                border: 1px solid #999999;
                border-collapse: collapse;
            }
            table {
                width:40%;
                min-width: 600px;
            }
            th, td {
                padding: 10px;
                text-align: left;    
            }
            table tr:nth-child(odd) {
                background-color: #F6F6F6;
            }
            h5 {
                color: #333333;
                margin: 0;
                padding: 10px;
            }
            pre {
                font-size: 14px;   
            }
            </style>
            </head>
            <body>
                <h3>$subject</h3>
                <table>
                <tr><th>Date:</th><td>$dtStamp</td></tr>
HTML;
                
        // Iterate array into table
        foreach ($errorData as $title => $value) {
            $message .= "<tr><th>$title:</th><td>$value</td></tr>";
        }
        
        // Rest of html email      
        $message .= <<< HTML
                </table>
                <h5>Generated by error $errorID page<h5>
            </body>
            </html>
HTML;
        
        // Headers
        $headers  = "MIME-Version: 1.0 \r\n";
        $headers .= "Content-type: text/html; charset=iso-8859-1 \r\n";
        $headers .= "From: $emailFrom\r\n";
        
        // Send Email
        mail($emailTo, $subject, $message, $headers);
    }
}